couchbase1:
  image: couchbase/server
  ports: 
        - '8094:8091'
  volumes:
    - ~/couchbase/node1:/opt/couchbase/var
  restart: always

couchbase2:
  image: couchbase/server
  ports: 
        - '8093:8091'
  volumes:
    - ~/couchbase/node2:/opt/couchbase/var
  restart: always
