#  with access, by name, to other vms
Vagrant.configure(2) do |config|
  config.vm.define "database", primary: true do |h|
    h.vm.box = "centos/7"
    h.vm.hostname =  "database"
    h.vm.network "private_network", ip: "192.168.135.148"
    h.vm.network "forwarded_port", guest: 22, host: "2200", id: "ssh"
    h.vm.provision :shell, inline: "echo 'export ANSIBLE_CONFIG=/vagrant/ansible/ansible.cfg' >> /home/vagrant/.bash_profile"
    h.vm.provision :shell, inline: 'sudo yum install -y yum-utils device-mapper-persistent-data lvm2;  sudo yum install python-requests; sudo yum-config-manager  --add-repo https://download.docker.com/linux/centos/docker-ce.repo; sudo yum install -y docker-ce; sudo systemctl enable docker; sudo systemctl start docker; sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose; sudo chmod +x /usr/local/bin/docker-compose'
    h.vm.provision :shell, :inline => <<'EOF'
	if [ ! -f "/home/vagrant/.ssh/id_rsa" ]; then
  ssh-keygen -t rsa -N "" -f /home/vagrant/.ssh/id_rsa
fi
cp /home/vagrant/.ssh/id_rsa.pub /vagrant/control.pub
cat << 'SSHEOF' > /home/vagrant/.ssh/config
Host *
  StrictHostKeyChecking no
  UserKnownHostsFile=/dev/null
SSHEOF
chown -R vagrant:vagrant /home/vagrant/.ssh/
EOF
  end

end
